title: Laura Gallegos
logo: https://media.licdn.com/dms/image/v2/D4E03AQGgCrjo-4MHWA/profile-displayphoto-shrink_200_200/B4EZO9JweLHkAY-/0/1734045272287?e=1744243200&v=beta&t=re_1BzT5-Kz71Pfk34LBzHaZsmrUrtNYBcliIOLHvew
description: Here you´ll find some interesting projects in wich I´ve been working as Data Scientist
#show_downloads: true
theme: jekyll-theme-minimal
